# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: FEniCS 22 tutorial
author: The FEniCS project
logo: fenics_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

  # Set timeout for any example to 20 minutes
  timeout: 1800

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jorgensd/fenics22-tutorial # Online location of your book
  path_to_book: . # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

parse:
  myst_enable_extensions:
    - "amsmath"
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_admonition"
    - "html_image"
    - "linkify"
    - "replacements"
    - "smartquotes"
    - "substitution"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

exclude_patterns: [README.md]

# Add HTML generated figures here
sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.intersphinx"
    - "sphinx_codeautolink"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"

  config:
    codeautolink_concat_default: True
    intersphinx_mapping:
      basix: ["https://docs.fenicsproject.org/basix/v0.10.0/python/", null]
      ffcx: ["https://docs.fenicsproject.org/ffcx/v0.10.0/", null]
      ufl: ["https://docs.fenicsproject.org/ufl/2025.2.0.post0/", null]
      dolfinx:
        ["https://docs.fenicsproject.org/dolfinx/v0.10.0.post0/python", null]
      petsc4py: ["https://petsc.org/release/petsc4py", null]
      mpi4py: ["https://mpi4py.readthedocs.io/en/stable", null]
      numpy: ["https://numpy.org/doc/stable/", null]
      pyvista: ["https://docs.pyvista.org/", null]
      matplotlib: ["https://matplotlib.org/stable/", null]

    html_extra_path:
      ["mesh.html", "wavenumber.html", "Abs(u).html", "beam.html", "w.html"]
    html_last_updated_fmt: "%b %d, %Y"
    suppress_warnings: ["mystnb.unknown_mime_type"]
