name: Test tutorial against DOLFINx nightly build

on:

  push:
    branches: [main]

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "* 9 * * 1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-nightly:
    runs-on: ubuntu-22.04
    container: dolfinx/lab:nightly

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install jupyter-book


      - name: Test building the book
        run: 
          PYVISTA_JUPYTER_BACKEND=static PYVISTA_OFF_SCREEN=false jupyter-book build  -W .
